name: 'Action'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Test with Docker Compose
        run: |
          docker-compose up --build --abort-on-container-exit tests

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      
      - name: Deploy to Staging
        run: |
          docker-compose up -d app

      - name: Set Staging URL
        id: deploy-staging
        run: echo "url=https://staging.example.com" >> $GITHUB_ENV

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Deploy to Production
        run: |
          docker-compose up -d app

      - name: Set Production URL
        id: deploy-production
        run: echo "url=https://production.example.com" >> $GITHUB_ENV